
services:
  postgres:
    image: kibaes/postgres-logical-replication-dev:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: playground
    ports:
      - "54320:5432"
    volumes:
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
